services:
  db-init:
    build: ./db-init
    command: sh -lc "chmod +x ./docker/run.sh && ./docker/run.sh"
    ports:
      - ${DB_INIT_PORT:-3005}:${DB_INIT_PORT:-3005}
    env_file: .env
    networks:
      - ft_transendance
    volumes:
      - users_data:/usr/src/app/db
      - ./db-init:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${DB_INIT_PORT:-3000}/health"]
      interval: 5s
      timeout: 3s
      retries: 24

  auth-backend:
    build: ./auth-backend
    command: sh -lc "chmod +x ./docker/run.sh && ./docker/run.sh"
    ports:
      - ${AUTH_PORT:-8005}:${AUTH_PORT:-8005}
    env_file: .env
    networks:
      - ft_transendance
    volumes:
      - ./auth-backend:/usr/src/app
      - users_data:/usr/src/app/db
    # depends_on:
    #   db-init:
    #     condition: service_healthy
    healthcheck:
      # test: ["CMD", "curl", "-fsS", "http://localhost:8005/health"]
      test: ["CMD", "curl", "-fsS", "http://localhost:${AUTH_PORT:-8005}/health"]
      interval: 5s
      timeout: 3s
      retries: 24
      # disable: true

  frontend:
    build: ./frontend
    command: sh -lc "chmod +x ./docker/run.sh && ./docker/run.sh"
    ports:
      - ${FRONTEND_PORT:-8080}:${FRONTEND_PORT:-8080}
    networks:
      - ft_transendance
    depends_on:
      auth-backend:
        condition: service_healthy
      usr-manag:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./frontend:/app

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web UI port
    networks:
      - ft_transendance
    env_file: .env

  usr-manag:
    build: ./usr-manag
    command: sh -lc "chmod +x ./docker/run.sh && ./docker/run.sh"
    ports:
      - ${USR_MANAG_PORT:-4000}:${USR_MANAG_PORT:-4000}
    networks:
      - ft_transendance
    # depends_on:
    #   db-init:
    #     condition: service_healthy
    #   auth-backend:
    #     condition: service_healthy
    #   mailpit:
    #     condition: service_healthy
    volumes:
      - ./usr-manag:/usr/src/app
      - users_data:/usr/src/app/db
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${USR_MANAG_PORT:-4000}/health"]
      interval: 30s
      timeout: 10s
      retries: 24

  prometheus:
    build: ./monitoring/prometheus
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    networks:
      - ft_transendance
    depends_on:
      # db-init:
      #   condition: service_healthy
      # usr-manag:
      #   condition: service_healthy
      auth-backend:
        condition: service_healthy
      # frontend:
      #   condition: service_healthy
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    develop:
      watch:
        - path: ./monitoring/prometheus
          action: restart
    env_file: .env

  grafana:
    image: grafana/grafana:latest
    ports:
      - ${GRAFANA_PORT:-4010}:${GRAFANA_PORT:-4010}
    networks:
      - ft_transendance
    environment:
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT:-4010}
    depends_on:
      prometheus:
        condition: service_started
    env_file: .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
  chat:
    build: ./chat
    command: sh -lc "chmod +x ./docker/run.sh && ./docker/run.sh"
    ports:
      - ${CHAT_PORT:-8006}:${CHAT_PORT:-8006}
    networks:
      - ft_transendance
    depends_on:
      db-init:
        condition: service_healthy
      auth-backend:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    env_file: .env

networks:
  ft_transendance:
    driver: bridge

volumes:
  users_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/transendance_volumes/users_db

  grafana_data:
    driver: local
    
  prometheus_data:
    driver: local