global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: auth-backend
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-backend:8005']
        labels:
          service: auth-backend
  - job_name: usr_manag
    metrics_path: /metrics
    static_configs:
      - targets: ['usr-manag:4000']
        labels:
          service: usr-manag