services:
  auth-backend:
    build: ./auth-backend
    command: npm run dev  
    ports:
      - 8005:8005
    env_file: ./auth-backend/.env
    networks:
      - ft_transendance
    volumes:
      - ./auth-backend:/usr/src/app
      - /usr/src/app/node_modules
      - auth_db_data:/usr/src/app/db
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8005/health"]
      interval: 5s
      timeout: 3s
      retries: 24

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 8080:8080
    networks:
      - ft_transendance
    depends_on:
      auth-backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web UI port
    networks:
      - ft_transendance
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1

  usr-manag:
    build: ./usr-manag
    command: npm start
    ports:
      - 4000:4000
    networks:
      - ft_transendance
    depends_on:
      auth-backend:
        condition: service_healthy
    volumes:
      - ./usr-manag:/usr/src/app
      - /usr/src/app/node_modules


networks:
  ft_transendance:
    driver: bridge

volumes:
  auth_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/leetsolutions1337/trancendance_volumes/auth-db